- python/openassetio_mediacreation/trait/__init__.py
- tests/python/openassetio_mediacreation/trait/test___init__.py
Sketches of how timeline items may be represented. It raises the interesting question of whether some traits may be applicable to both entities and locales?
Committing to facilitate discussion, and enable the `otio-openassetio` PoC to switch to traits.
> [Library] Add sketch of timeline traits

- decisions/DR001-Locatable-content-traits.md
Moved from https://github.com/TheFoundryVisionmongers/OpenAssetIO/pull/356, as it belongs in this repository.
> [Docs] Add `locatableContent` traits design decision record

- README.md
- pyproject.toml
- python/openassetio_mediacreation/trait/__init__.py
- python/openassetio_mediacreation/trait/entity.py
- setup.py
- tests/python/openassetio_mediacreation/trait/test___init__.py
- tests/python/openassetio_mediacreation/trait/test_entity.py
Closes #9 
Use the PyPI version of OpenAssetIO as the dependency, rather than requiring a manual build.
In prelude to moving traitgen over and automatically generating these traits.
> [Build] Add managed OpenAssetIO dependency

- .github/workflows/build-wheels.yml
- .github/workflows/deploy-pypi.yml
- README.md
- RELEASE_NOTES.md
- pyproject.toml
Closes #11 
Provides the standard build wheels and publish process for MediaCreation.
Have updated to alpha 2 so a publish can be performed strait away
TestPyPI publish can be perused here : https://test.pypi.org/project/openassetio-mediacreation/1.0.0a1.dev0/
> MediaCreation Publish PyPI

- README.md
The instructions said 'after installing', which you could do from a pip install, but I'd imagine the usual use case is for developers?
> [Docs] Update test instructions

- RELEASE_NOTES.md
- tests/python/openassetio_mediacreation/test_imports.py
- traits.yml
Adds traits recently removed from OpenAssetIO and a few other minor improvements noticed on the way.
Closes https://github.com/OpenAssetIO/OpenAssetIO/issues/717
> Migrate managementPolicy traits from OpenAssetIO

- CMakeLists.txt
Original implementation didn't include traits.yml in the install folder. This copies the file from the project binary directory to the data install directory under
openassetio-traitgen/openassetio-mediacreation.yml.
Fixes #26
> [Build] Include traits.yml with C++ dist

- RELEASE_NOTES.md
- tests/cpp/test.cpp
- tests/python/openassetio_mediacreation/test_imports.py
- traits.yml
OpenAssetIO used to have `entityName` and `entityDisplayName` methods. It makes more sense to use a trait for entity identity as the specifics of this may well be industry specific, and it potentially avoids several additional API calls in common scenarios.
The definitions are largely lifed from the old API methods, with minor massaging of property names to attempt to be more coherent.
Part of https://github.com/OpenAssetIO/OpenAssetIO/issues/837
> Add `DisplayName` trait in `identity` namespace

- RELEASE_NOTES.md
- tests/cpp/test.cpp
- tests/python/openassetio_mediacreation/test_imports.py
- traits.yml
These had originally been added for the `otio-openassetio` prototype. This has since stopped using them on the basis that highly specific locales tend to preclude batching. Until all this settles down, and we have a significant number of real integrations producing scenarios where we do need more information, we should aim to keep the locale as minimal as possible to maximize batching opportunities.
> [Traits] Remove speculative timeline traits

- README.md
- tests/cpp/test.cpp
We previously explicitly imported all the C++ headers. This served to verify that the YAML produced the correct outputs. We also do this in Python though, so this is really mostly testing TraitGen.
We have a rule of thumb that we don't re-test auto-generated code, and the C++ tooling requirements have been noted to form a barrier to entry to contributors who may work mostly in the Python world.
As, assuming we trust TraitGen, all generated headers are still imported by the package header, this commit removes the explicit imports of individual trait headers. This means we should still test that all shipping headers are syntax correct.
> Simplify C++ header imports in tests

- RELEASE_NOTES.md
- tests/python/openassetio_mediacreation/test_imports.py
- traits.yml
Discussed with @foundrytom on Friday, I'd like to add this trait for the SIGGRAPH review workflow demo. I'll ask the MovieLabs manager to enable EasyCLA on this repo...
> [Traits] Add placeholder auth.BearerToken trait for SIGGRAPH demo

- .github/workflows/test.yml
- CMakeLists.txt
- RELEASE_NOTES.md
- cmake/ThirdParty.cmake
Closes #49 
Adds the ability to optionally and additionally generate the python package when running under the cmake build system.
This is intended to enable hybrid hosts/managers to get both of their required libraries out without needing to call out/synchronize between multiple build systems (cmake & pip)
Adds `OPENASSETIO_MEDIACREATION_GENERATE_PYTHON` as the toggle variable, and `OPENASSETIO_MEDIACREATION_PYTHON_SITEDIR` as the location override variable.
Brings in the python part of `ThirdParty.cmake` from the OpenAssetIO directory to do the path intuition for the sitedir.
Added a test that invokes the cmake generation and runs the import test suite by setting the pythonpath.
> [Build] Add hybrid python generation to cmake.

- traits.yml
The choice for reverse chronological comes from common use patterns.
> [Traits] Clarify canonical use of version related traits

- .github/workflows/test.yml
- RELEASE_NOTES.md
- pyproject.toml
This ensures backwards compatability whilst commercially available hosts are still using `a14`.
Closes #60
> [Build] Pin `openassetio-traitgen` to `v1.0.0a7`

- RELEASE_NOTES.md
- tests/python/openassetio_mediacreation/test_imports.py
- traits.yml
The core API will be providing a proper mechanism to introspect this aspect of a managers operation:
https://github.com/OpenAssetIO/OpenAssetIO/issues/1209
Closes #67
This poses the question about what do we want to do in the examples:
- Leave it, itll be reet.
- Update to `kDerived` (or whatever)
> [Traits] Remove `ResolvesFutureEntities` trait

- RELEASE_NOTES.md
- examples/resources/requirements.txt
- pyproject.toml
Bump OpenAssetIO dependency now that `ResolvesFutureEntities` has been removed in favour of a `managementPolicy` query in the core API.
Bump BAL dependency to minimum compatible with latest OpenAssetIO version 1.0.0-beta.2.0 (newly required method, `entityTraits`).
> [Release] Bump version to v1.0.0-alpha.8

- examples/file_path_url_converter.ipynb
Following on from OpenAssetIO/OpenAssetIO#1117 add a Jupyter Notebook illustrating the usage of `FilePathUrlConverter`.
This is in no way complete, and was used as part of a live demo in sprint review. It seems like useful documentation nonetheless and worth keeping in the repo.
> [Docs] Add FilePathUrlConverter notebook

- examples/file_path_url_converter.ipynb
Part of OpenAssetIO/OpenAssetIO#1257. The
`FilePathUrlConverter.pathFromUrl` function now converts long Windows file URLs, which exceed the Windows `MAX_PATH` limit, to UNC device paths.
> [Docs] Long Windows paths in FilePathUrlConverter notebook

- .github/workflows/examples.yml
- .github/workflows/test.yml
- examples/management_policies.ipynb
- examples/resources/management_policies/bal_database.json
GitHub's `macos-latest` runner is now ARM based. Until we build ARM wheels for the `openassetio` MacOS package, we must downgrade the runner to an x86 machine.
Also, BAL was updated and the `managementPolicy` notebook no longer worked. This was fixed as a ninja commit in #69, but at time of writing has still not been merged. So cherry-pick the fix from there.
> [CI] Use x86 MacOS for tests

- examples/generic_republish.ipynb
- examples/querying_entity_traits.ipynb
- examples/resources/generic_republish/bal_database.json
- examples/resources/generic_republish/openassetio_config.toml
- examples/resources/querying_entity_traits/bal_database.json
- examples/resources/querying_entity_traits/openassetio_config.toml
Add a notebook illustrating the usage of `entityTraits`, as specified in OpenAssetIO/OpenAssetIO#31. 
Add another notebook illustrating advanced usage of `entityTraits` in a generic resolve-and-republish workflow.
The idea in the first instance is to provoke discussion and provide a reference as the feature is further refined.
An ideal outcome is that this document continues to be iterated as the feature(s) is developed, incorporating changes in design as well as new corner cases that need defining. 
Eventually this should lead to an executable specification of the feature, which also serves as example documentation.
The notebook has dependencies on work in other repos, in particular
- OpenAssetIO/OpenAssetIO#31
- OpenAssetIO/OpenAssetIO#1209
- OpenAssetIO/OpenAssetIO#1217
- …
> [Docs] Add Jupyter Notebook illustrating entityTraits

- examples/string_token_substitution.ipynb
Closes #91. A gaping hole in OpenAssetIO standardisation is how strings with embedded substitution tokens should be communicated between a host and a manager. Hosts and managers must agree on the syntax of substitution tokens, what tokens are available, and the meaning of those tokens.
So add a notebook explaining the OpenAssetIO approach to solving this, including example usage of the `subtitute` utility function.
The notebook will fail unless/until the `substitute` function is available. See https://github.com/OpenAssetIO/OpenAssetIO/issues/1213
> Add string substitution notebook

- .github/build_openassetio/action.yml
- .github/workflows/examples.yml
- .github/workflows/test.yml
- examples/hybrid_plugin_system.ipynb
- examples/resources/hybrid_plugin_system/SimpleHybridManager/.clang-format
- examples/resources/hybrid_plugin_system/SimpleHybridManager/.clang-tidy
- examples/resources/hybrid_plugin_system/SimpleHybridManager/README.md
- examples/resources/hybrid_plugin_system/SimpleHybridManager/cmake-format.yaml
- examples/resources/hybrid_plugin_system/SimpleHybridManager/linter-requirements.txt
- examples/resources/hybrid_plugin_system/SimpleHybridManager/plugin/PyComponentOfSimpleHybridManager.py
- examples/resources/hybrid_plugin_system/SimpleHybridManager/pyproject.toml
- examples/resources/hybrid_plugin_system/SimpleHybridManager/src/CMakeLists.txt
- examples/resources/hybrid_plugin_system/SimpleHybridManager/src/CppComponentOfSimpleHybridManager.cpp
- examples/resources/hybrid_plugin_system/openassetio_config.toml
- examples/resources/requirements.txt
Add notebook for the design, documentation and e2e testing of the Hybrid Plugin System introduced in https://github.com/OpenAssetIO/OpenAssetIO/issues/1202
Current [rendered version](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/blob/669f14394e3acb83dd62e1e1976d6c680f1ef001/examples/hybrid_plugin_system.ipynb)
_Notebook Driven Development_ :wink:
> Add hybrid plugin system notebook

- pyproject.toml
Closes #107. Re-release commit due to missed pyproject version bump.
> [Release] Bump version to v1.0.0-alpha.11

- .github/workflows/build-wheels.yml
GitHub has now removed `actions/upload-artifact` v3. See OpenAssetIO/OpenAssetIO#1444 for more info on consequences.
However, luckily in this repo we don't require significant changes.
> Bump actions/upload-artifact to v4

- README.md
It turns out in practice that users usually want both the C++ and Python component when generating the trait library using CMake. There was no mention that the Python component must be enabled using a CMake variable.
So add a small tweak to the README so that the default instructions enable the Python component.
> Update README CMake instructions to include Python by default

- .github/workflows/test.yml
- RELEASE_NOTES.md
- pyproject.toml
- traits.yml
Part of OpenAssetIO/OpenAssetIO#1302.
Add initial tranche of traits that were found to be useful when prototyping UI delegation, and update some existing traits. In particular:
Add traits for sets of images. An image collection could be a manifest, directory, archive file, templated path, etc, containing one or more images. An image sequence specialises image collection with a frame range, implying the images in the collection are ordered. E.g. an image collection with a MIME type of "inode/directory" refers to a directory containing images.
Expand on MIME type usage in LocatableContent trait. In particular, support for multiple MIME types in a single field; and sources of common MIME types.
> Add initial `ui` and `uiPolicy` traits

- examples/file_path_url_converter.ipynb
> [Docs] Correct notebook FilePathUrlConverter -> FileUrlPathConverter
